
all: 
	g++ jacobi_sum.cpp -o jacobi_sum
	g++ jacobi_mat.cpp -o jacobi_mat
	g++ gs_sum.cpp -o gs_sum
	g++ gs_mat.cpp -o gs_mat

jacobi_sum:
	g++ jacobi_sum.cpp -o jacobi_sum

jacobi_mat:
	g++ jacobi_mat.cpp -o jacobi_mat

gs_sum:
	g++ gs_sum.cpp -o gs_sum

gs_mat:
	g++ gs_mat.cpp -o gs_mat

clean_entrys:
	rm ./salida.txt
	rm ./entrada.txt

clean:
	rm ./jacobi_mat
	rm ./jacobi_sum
	rm ./gs_mat
	rm ./gs_sum